
const humorsArray = [
    "Why did the programmer bring a flashlight? To debug in the dark.",
    "What do you call a programmer who writes music? A code composer.",
    "Why did the loop go to therapy? It had too many breakups.",
    "How do programmers flirt? They send you a 'commit' message.",
    "Why was the database always calm? It had a lot of inner joins.",
    "What 's a programmers favorite exercise? Running a script.",
    "Why did the coder bring a map? To navigate the stack overflow.",
    "Why don t programmers argue? Because they just merge conflicts.",
    "What did the error say to the developer? 'You 've got no class!'",
    "Why did the Python programmer prefer snakes? Because they don 't use curly braces.",
    "How do you make a programmer smile? Show them a well-indented code.",
    "Why was the computer a good musician? It had perfect timing loops.",
    "What do you call a programmer who fixes bugs on weekends? A debug ninja.",
    "Why did the API break up with the frontend? It couldn 't handle the requests.",
    "Why did the coder sleep at the office? He wanted to be closer to the server.",
    "What 's a programmer 's favorite dessert? Binary chocolate cake (0s and 1s).",
    "Why did the developer wear glasses? To improve his code vision.",
    "How do programmers party? They raise a toast to the host.",
    "Why was the software engineer so quiet? He was in a recursive loop of thoughts.",
    "What did the coder say at the bar? 'I 'll have a shot of whiskey and a stack trace.'",
    "Why did the programmer prefer dark mode? Because the light attracted bugs.",
    "Why do programmers prefer coffee? Because it pairs well with everything.",
    "How do you comfort a JavaScript bug? You console it.",
    "Why did the coder bring a ladder to work? To take his career to the next level.",
    "Why did the developer go broke? Because he used up all his cache.",
    "What 's a programmer 's favorite hangout place? The Foo Bar.",
    "Why did the programmer quit? Because he didn 't get arrays.",
    "How do you know someone is a programmer? Don 't worry, they 'll tell you a byte about it.",
    "Why was the computer cold? It left its Windows open.",
    "Why did the programmer get stuck in the shower? The instructions were in XML.",
    "What do you call a programmer from Finland? A Nordic coder.",
    "Why did the function date the variable? Because it had a good type.",
    "Why don 't programmers play chess? They 're afraid of anything with a checkmate.",
    "What 's a programmer 's favorite song? 'Another One Bites the Dust' by Queen—perfect for debugging.",
    "Why did the programmer bring a broom? To sweep up the memory leaks.",
    "How do programmers stay cool? They have lots of fans (and good airflow).",
    "Why did the developer get lost? Because he didn 't have a pointer.",
    "What do you call a lazy programmer? A code slacker.",
    "Why was the JavaScript developer sad? Because he didn 't know how to 'null' his feelings.",
    "Why did the programmer prefer the terminal? Because it had a better interface with his soul.",
    "Why did the programmer bring a ladder to the interview? To step up his skills.",
    "What 's a coder 's favorite dance? The algorithm shuffle.",
    "Why did the bug report get ignored? It wasn 't in the right thread.",
    "How do programmers stay in shape? By lifting stacks and pushing commits.",
    "Why did the developer stare at the orange juice? It said 'concentrate' on the label.",
    "What do you call a programmer who writes poetry? A code versifier.",
    "Why was the computer tired? It had too many sleepless nights compiling.",
    "How do you know a programmer is on vacation? They 're still debugging in their dreams.",
    "Why did the function refuse to work? It had too many arguments.",
    "What 's a programmer 's favorite movie? The Matrix—full of code redpills.",
    "Why did the coder bring a magnet? To attract more bugs.",
    "How do programmers make decisions? They flip a boolean.",
    "Why was the software slow? It was running on ancient hardware and bad puns.",
    "What did the coder say to the compiler? 'You 're giving me too many errors!'",
    "Why did the programmer get locked out? He forgot his private key.",
    "What 's a coder 's favorite sport? Syntax sprinting.",
    "Why did the loop get dizzy? It kept going around in circles.",
    "How do programmers relax? By watching 'byte'-sized videos.",
    "Why was the code so clean? The developer used a lint brush.",
    "What do you call a programmer 's dog? A fetch-executor.",
    "Why did the programmer bring a clock? To keep track of his runtime.",
    "What 's a coder 's favorite game? Stack overflow challenge.",
    "Why did the bug go to school? To improve its exception handling.",
    "How do programmers greet each other? With a 'git push' handshake.",
    "Why was the database always calm? It had a lot of inner joins.",
    "What do you call a programmer who loves nature? A tree-traversing coder.",
    "Why did the developer bring a mirror? To reflect on his code.",
    "How do programmers fight? With a battle of brackets.",
    "Why did the script fail? It couldn 't handle the plot twist.",
    "What 's a programmer 's favorite snack? Microchips.",
    "Why did the coder wear headphones? To tune out the noise from bad code.",
    "How do you make a programmer smile on Monday? Tell them it 's Friday in binary.",
    "Why was the software engineer so good at poker? He knew when to fold the stack.",
    "What did the debugger say? 'I 've got your backtrace covered.'",
    "Why did the programmer bring a calculator? To count his bugs.",
    "What 's a coder 's favorite holiday? Halloween—full of spooky bugs.",
    "Why did the function get promoted? It had a great return value.",
    "How do programmers travel? They take the shortest path algorithm.",
    "Why was the code so moody? It had too many conditional statements.",
    "What do you call a programmer 's cat? A purr-grammer.",
    "Why did the programmer bring a book? To read up on error codes.",
    "What 's a coder 's favorite instrument? The code-ophone.",
    "Why did the bug hide? It didn 't want to be patched.",
    "How do programmers stay warm? With a lot of hot patches.",
    "Why was the server so loud? It was shouting error logs.",
    "What do you call a programmer who loves art? A pixel pusher.",
    "Why did the developer bring a net? To catch floating-point errors.",
    "How do programmers cook? They follow a strict recipe algorithm.",
    "Why did the code crash the party? It had too many unhandled exceptions.",
    "What 's a programmer 's favorite drink? Java—strong and black.",
    "Why did the coder bring a ruler? To measure his code length.",
    "How do programmers apologize? With a 'git revert' and a sorry note.",
    "Why was the software so slow? It was stuck in a while(true) loop.",
    "What did the coder say to the deadline? 'I 'll push it to the next sprint.'",
    "Why did the programmer bring a flashlight? To debug the dark corners.",
    "What 's a coder 's favorite flower? The binary rose (0s and 1s).",
    "Why did the function break up? It couldn 't handle the parameters.",
    "How do programmers fish? With a net of pointers.",
    "Why was the code so happy? It finally passed all tests.",
    "What do you call a programmer 's train? A commit express.",
    "Why did the programmer bring a compass? To navigate the codebase.",
    "What 's a coder 's favorite candy? Syntax sugar.",
    "Why did the bug escape? It found a loophole.",
    "How do programmers celebrate? With a successful merge party.",
    "Why was the database so organized? It had perfect indexing.",
    "What do you call a programmer who loves space? A cosmic coder.",
    "Why did the developer bring a fan? To cool down the overheating code.",
    "How do programmers meditate? By focusing on their stack trace.",
    "Why did the script get embarrassed? It exposed its private variables.",
    "What 's a programmer 's favorite bird? The loop-gull.",
    "Why did the coder bring a hammer? To fix the hard bugs.",
    "How do programmers date? They match on a binary scale.",
    "Why was the software so confident? It had a strong type system.",
    "What did the debugger say? 'Gotcha!'",
    "Why did the programmer bring a map? To find the missing semicolon.",
    "What 's a coder 's favorite car? A parallel-parked sedan.",
    "Why did the function get lonely? It had no callers.",
    "How do programmers swim? With a float array.",
    "Why was the code so poetic? It had beautiful indentation.",
    "What do you call a programmer 's pet fish? A byte-fish.",
    "Why did the programmer bring a pillow? For a quick nap in the debug session.",
    "What 's a coder 's favorite fruit? A binary apple (0 or 1).",
    "Why did the bug multiply? It found a recursive hideout.",
    "How do programmers shop? They optimize for the best deal.",
    "Why was the server so chatty? It had too many open ports.",
    "What do you call a programmer who loves history? A legacy coder.",
    "Why did the developer bring a brush? To clean up the messy code.",
    "How do programmers paint? With pixel-perfect strokes.",
    "Why did the code get detention? It had too many runtime errors.",
    "What 's a programmer 's favorite shoe? A slipper with a good sole.",
    "Why did the coder bring a clock? To time his algorithms.",
    "How do programmers argue? With a battle of logic gates.",
    "Why was the software so smart? It learned from its exceptions.",
    "What did the coder say to the bug? 'You 're not in my scope!'",
    "Why did the programmer bring a backpack? To carry his tools.",
    "What 's a coder 's favorite tree? A binary search tree.",
    "Why did the function get tired? It had too many calls.",
    "How do programmers fish? With a hook and a pointer.",
    "Why was the code so friendly? It had open interfaces.",
    "What do you call a programmer 's hat? A cap with a debug visor.",
    "Why did the programmer bring a kite? To fly high in the cloud.",
    "What 's a coder 's favorite game? Memory match.",
    "Why did the bug get promoted? It was good at sneaking through tests.",
    "How do programmers travel light? With a minimal payload.",
    "Why was the database so quiet? It was in a transaction lock.",
    "What do you call a programmer who loves math? A numeric nerd.",
    "Why did the developer bring a torch? To light up the dark code.",
    "How do programmers dance? With a synchronized loop.",
    "Why did the script get lost? It missed a path variable.",
    "What 's a programmer 's favorite animal? A recursive turtle.",
    "Why did the coder bring a scale? To balance his workload.",
    "How do programmers cheer? With a 'commit' chant.",
    "Why was the software so flexible? It had dynamic typing.",
    "What did the debugger say to the code? 'Let 's step through this.'",
    "Why did the programmer bring a notebook? To log his thoughts.",
    "What 's a coder 's favorite planet? Mars—full of red code.",
    "Why did the function get a raise? It returned great value.",
    "How do programmers climb? With a stack ladder.",
    "Why was the code so musical? It had a good rhythm section.",
    "What do you call a programmer 's boat? A float with a pointer.",
    "Why did the programmer bring a umbrella? To shield from runtime showers.",
    "What 's a coder 's favorite puzzle? A logic gate maze.",
    "Why did the bug join a band? It loved playing error notes.",
    "How do programmers relax? With a break statement.",
    "Why was the server so strong? It handled heavy loads.",
    "What do you call a programmer who loves food? A byte chef.",
    "Why did the developer bring a lens? To focus on the bugs.",
    "How do programmers sing? In perfect sync with the loop.",
    "Why did the code get a timeout? It took too long to execute.",
    "What 's a programmer 's favorite tool? A debug wrench.",
    "Why did the coder bring a watch? To time his iterations.",
    "How do programmers race? With a sprint merge.",
    "Why was the software so brave? It faced all exceptions.",
    "What did the coder say to the server? 'Don 't crash on me!'",
    "Why did the programmer bring a bag? To carry his scripts.",
    "What 's a coder 's favorite season? Fall—time to debug leaves.",
    "Why did the function get applause? It handled all inputs.",
    "How do programmers garden? With a root directory.",
    "Why was the code so tidy? It had a strict lint policy.",
    "What do you call a programmer 's kite? A cloud flyer.",
    "Why did the programmer bring a candle? To light the way through the code.",
    "What 's a coder 's favorite sport? Binary bowling.",
    "Why did the bug get a medal? It survived the patch.",
    "How do programmers plan? With a flow chart.",
    "Why was the database so wise? It stored all the knowledge.",
    "What do you call a programmer who loves travel? A roaming coder.",
    "Why did the developer bring a shovel? To dig into the stack.",
    "How do programmers draw? With a vector pen.",
    "Why did the script get a timeout? It couldn 't keep up with the clock.",
    "What 's a programmer 's favorite fish? A byte-sized trout.",
    "Why did the coder bring a compass? To find the true north of the code.",
    "How do programmers toast? With a 'git push' cheer.",
    "Why was the software so patient? It waited for the right input.",
    "What did the debugger say to the error? 'I 'll fix you up!'",
    "Why did the programmer bring a journal? To log his thoughts.",
    "What 's a coder 's favorite weather? A clear cache day.",
    "Why did the function get a vacation? It needed a break from calls.",
    "How do programmers sail? With a navigation stack.",
    "Why was the code so elegant? It had perfect syntax.",
    "What do you call a programmer 's dream? A bug-free utopia."
];



  const randomIndex = Math.floor(Math.random() * humorsArray.length);
  const randomPlaceholder = humorsArray[randomIndex];

  const textarea = document.getElementById("expandingInput");
  textarea.placeholder = randomPlaceholder;

  /*The above code gives us a random placeholder in the text area*/


  const regenerateBtn = document.getElementById("regenerateBtn");
  regenerateBtn.addEventListener("click", () =>{
    const randomIndex = Math.floor(Math.random() * humorsArray.length);
  const randomPlaceholder = humorsArray[randomIndex];

  const textarea = document.getElementById("expandingInput");
  textarea.placeholder = randomPlaceholder;

  /*The above ensures when the regenerate button is clicked a random humor is updated to the textarea*/

  });